### ISSUE TITLE
Have you seen this overview of discussed Taproot activation proposals?

### ISSUE THREAD

**Issue by murchandamus** [taprootactivation/Taproot-Activation#2]
Hi Alejandro,

When I linked your website in ##taproot-activation on IRC, someone mentioned the [Taproot activation proposals](https://en.bitcoin.it/wiki/Taproot_activation_proposals) wiki page. I was just wondering whether you had seen it, it might be a nice source of material to elaborate the proposals here on this page.

**Comment by moneyball** [comment]
I agree that would be a good resource to link to

**Comment by AlejandroDeLaTorre** [comment]
thanks for the suggestion, will add the link to the page.

**Comment by jonasnick** [comment]
Hi,

I appreciate this effort to allow stakeholders to signal support for activation methods. Related to the OP, you can see that the Taproot wiki page does not include a proposal that activates via BIP9. BIP8 has a mode, commonly referred to as BIP8(lockinontimeout=false), that functions similar to BIP9, but is not exactly the same, because it fixes a bug and allows for parallel deployments. It's already the case that many people confuse BIP8 with BIP8(true), resulting in unnecessary discussion and division. In particular, it's confusing to signal support for an activation method (BIP9) that has very little chance of being used. Ideally, taprootactivation.com would match the terminology of the wiki page and replace mentions of BIP9 with BIP8(false).

**Comment by AlejandroDeLaTorre** [comment]
Hello,

Thanks for the feedback. The terminology now matches those of the wiki page.

**Comment by jonasnick** [comment]
@AlejandroDeLaTorre looks good. Thank you.

**Comment by murchandamus** [comment]
I've opened PR #3 to clarify the history of BIP9 and BIP8 a bit more. Review welcome.
